[logger]
level = "INFO"
file_path = "./logs/log.out"

[server]
addr_http = ":8088"
addr_grpc = ":8081"

[storage]
host = "localhost"
port = "5432"
database = "calendar"
ssl = "disable"
is_mem = false

