run:
  linters-settings:
    funlen:
      lines: 150
      statements: 80

  linters:
    disable-all: false
    enable-all: true
    disable:
      - maligned
      - interfacer
      - scopelint
      - golint